(deftheme andy
  "Created 2019-10-05.")

(custom-theme-set-variables
 'andy
 '(custom-safe-themes (quote ("84890723510d225c45aaff941a7e201606a48b973f0121cb9bcb0b9399be8cba" default)))
 '(package-selected-packages (quote (fireplace notmuch ess elpy)))
 '(column-number-mode t)
 '(tool-bar-mode nil)
 '(ansi-color-names-vector ["#3F3F3F" "#CC9393" "#7F9F7F" "#F0DFAF" "#8CD0D3" "#DC8CC3" "#93E0E3" "#DCDCCC"]))

(custom-theme-set-faces
 'andy
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#F0DFAF" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#D0BF8F" :underline t :weight normal))))
 '(cursor ((t (:foreground "#DCDCCC" :background "#FFFFEF"))))
 '(widget-field ((t (:foreground "#DCDCCC" :background "#6F6F6F"))))
 '(escape-glyph ((t (:foreground "#F0DFAF" :weight bold))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(header-line ((t (:foreground "#F0DFAF" :background "#2B2B2B" :box (:line-width -1 :style released-button)))))
 '(highlight ((t (:background "#383838"))))
 '(success ((t (:foreground "#7F9F7F" :weight bold))))
 '(warning ((t (:foreground "#DFAF8F" :weight bold))))
 '(tooltip ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(compilation-info ((t (:foreground "#BFEBBF" :underline t))))
 '(compilation-line-number ((t (:foreground "#F0DFAF"))))
 '(compilation-mode-line-exit ((t (:foreground "#9FC59F" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#CC9393" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#F0DFAF" :weight bold))))
 '(completions-annotations ((t (:foreground "#656555"))))
 '(match ((t (:background "#2B2B2B" :foreground "#DFAF8F" :weight bold))))
 '(Info-quoted ((t (:inherit font-lock-constant-face))))
 '(isearch ((t (:foreground "#D0BF8F" :weight bold :background "#5F5F5F"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#8C5353"))))
 '(lazy-highlight ((t (:foreground "#D0BF8F" :weight bold :background "#383838"))))
 '(menu ((t (:foreground "#DCDCCC" :background "#3F3F3F"))))
 '(minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#8FB28F" :background "#2B2B2B" :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 '(mode-line-buffer-id ((t (:foreground "#F0DFAF" :weight bold))))
 '(mode-line-inactive ((t (:foreground "#5F7F5F" :background "#383838" :box (:line-width -1 :style released-button)))))
 '(region ((((class color) (min-colors 89)) (:background "#2B2B2B")) (t :inverse-video t)))
 '(secondary-selection ((t (:background "#5F5F5F"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(vertical-border ((t (:foreground "#DCDCCC"))))
 '(font-lock-builtin-face ((t (:foreground "#DCDCCC" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#7F9F7F" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:foreground "#D0BF8F" :weight bold))))
 '(line-number ((t (:foreground "#6F6F6F" :background "#383838"))))
 '(line-number-current-line ((t (:inherit line-number :foreground "#D0BF8F"))))
 '(company-tooltip ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(company-tooltip-annotation ((t (:foreground "#DFAF8F" :background "#4F4F4F"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#DFAF8F" :background "#2B2B2B"))))
 '(company-tooltip-selection ((t (:foreground "#DCDCCC" :background "#2B2B2B"))))
 '(company-tooltip-mouse ((t (:background "#2B2B2B"))))
 '(company-tooltip-common ((t (:foreground "#9FC59F"))))
 '(company-tooltip-common-selection ((t (:foreground "#9FC59F"))))
 '(company-scrollbar-fg ((t (:background "#2B2B2B"))))
 '(company-scrollbar-bg ((t (:background "#5F5F5F"))))
 '(company-preview ((t (:background "#9FC59F"))))
 '(company-preview-common ((t (:foreground "#9FC59F" :background "#2B2B2B"))))
 '(diff-added ((t (:background "#2F4F2F" :foreground "#9FC59F"))))
 '(diff-changed ((t (:background "#555511" :foreground "#E0CF9F"))))
 '(diff-removed ((t (:background "#6C3333" :foreground "#DCA3A3"))))
 '(diff-refine-added ((t (:background "#3F5F3F" :foreground "#AFD8AF"))))
 '(diff-refine-changed ((t (:background "#888811" :foreground "#F0DFAF"))))
 '(diff-refine-removed ((t (:background "#7C4343" :foreground "#ECB3B3"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#5F5F5F")) (t (:background "#DCDCCC" :foreground "#3F3F3F"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#5F5F5F" :foreground "#DCDCCC" :weight bold)) (t (:background "#DCDCCC" :foreground "#3F3F3F" :weight bold))))
 '(flymake-error ((((supports :underline (:style wave))) (:underline (:style wave :color "#CC9393") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(flymake-warning ((((supports :underline (:style wave))) (:underline (:style wave :color "#DFAF8F") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#DFAF8F" :weight bold :underline t))))
 '(ivy-confirm-face ((t (:foreground "#7F9F7F" :background "#3F3F3F"))))
 '(ivy-current-match ((t (:foreground "#F0DFAF" :weight bold :underline t))))
 '(ivy-cursor ((t (:foreground "#3F3F3F" :background "#DCDCCC"))))
 '(ivy-match-required-face ((t (:foreground "#CC9393" :background "#3F3F3F"))))
 '(ivy-minibuffer-match-face-1 ((t (:background "#4F4F4F"))))
 '(ivy-minibuffer-match-face-2 ((t (:background "#5F7F5F"))))
 '(ivy-minibuffer-match-face-3 ((t (:background "#7F9F7F"))))
 '(ivy-minibuffer-match-face-4 ((t (:background "#8FB28F"))))
 '(ivy-remote ((t (:foreground "#8CD0D3" :background "#3F3F3F"))))
 '(ivy-subdir ((t (:foreground "#F0DFAF" :background "#3F3F3F"))))
 '(ido-first-match ((t (:foreground "#F0DFAF" :weight bold))))
 '(ido-only-match ((t (:foreground "#DFAF8F" :weight bold))))
 '(ido-subdir ((t (:foreground "#F0DFAF"))))
 '(ido-indicator ((t (:foreground "#F0DFAF" :background "#8C5353"))))
 '(outline-1 ((t (:inherit default :foreground "#DFAF8F"))))
 '(outline-2 ((t (:inherit default :foreground "#BFEBBF"))))
 '(outline-3 ((t (:inherit default :foreground "#7CB8BB"))))
 '(outline-4 ((t (:inherit default :foreground "#D0BF8F"))))
 '(outline-5 ((t (:inherit default :foreground "#93E0E3"))))
 '(outline-6 ((t (:inherit default :foreground "#9FC59F"))))
 '(outline-7 ((t (:inherit default :foreground "#8C5353"))))
 '(outline-8 ((t (:inherit default :foreground "#4C7073"))))
 '(show-paren-mismatch ((t (:foreground "#DCA3A3" :background "#6F6F6F" :weight bold))))
 '(show-paren-match ((t (:foreground "#DCDCCC" :background "#6F6F6F" :weight bold))))
 '(default ((t (:foreground "#DCDCCC" :background "#3F3F3F")))))

(provide-theme 'andy)
